### PR TITLE
Improve page 4

### PR DESCRIPTION
**Pull request by Aichnerc**
**Checklist:**

 
 - [x] Have you added an explanation of what your changes do and why you'd like them to be included?
 - [ ] Have you updated or added documentation for the change?
 - [x] Have you tested your changes with successful results?

**Type of Changes:**

 
 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [x] New feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change)

**What is the current behavior? (link to any open issues here)**
- Currently the GitHub repository name is "blue-lupi-homepage".
- Currently a text in the footer is wrong.
- Currently the Cookie Modal is missing a "learn more" button.
- Currently you can not manage your cookie selection.
- The cart is missing details about shipment.

**What is the new behavior (if this is a feature change)?**
- The GitHub repository name has been changed to "front".
- The text in the footer has been improved.
- A learn more button has been added.
- You can now manage your cookie selection at the /privacy page.
- A shipment note has been added to the cart.

**Other information**:
- The version is still v1.0.0, once it is building up to the first release.

### CODE REVIEW

**Review by pinterid — APPROVED** [review]
Looks good.

**Review by Aichnerc — COMMENTED** [review]
🐋 blub

**Review by schettn — APPROVED** [review]
LGTM

**Review by kleberbaum — APPROVED** [review]
Should be ok to merge.

**Pull request merged**
